#!/bin/bash

echo_green() {
  echo -e "\e[32m$1\e[39m"
}

echo_red() {
  echo -e "\e[31m$1\e[39m"
}

echo_magenta() {
  echo -e "\e[35m$1\e[39m"
}

user_home_dir=`eval echo ~$USER`

real_path=$(pwd)/polyglot_watcher

symlink_path=$user_home_dir/.local/bin/

echo_magenta "symlinking $real_path to $symlink_path"

ln -f -s $real_path $symlink_path

result=$?

if [[ $result == 0 ]]; then
  echo_green "It worked!"
  echo_green "You can run 'polyglot_watcher' from anywhere. Go wild"
else
  echo_red "Failed to setup the symlink. Oof"
fi
