#!/usr/bin/env bash

# Start the program in the background
exec "$@" &
pid1=$!

# Silence warnings from here on
#exec >/dev/null 2>&1

# Read from stdin in the background and
# kill running program when stdin closes
exec 0<&0 $(
  while read; do :; done
  kill -KILL $pid1 >/dev/null 2>&1
) &
pid2=$!

# Clean up
wait $pid1
ret=$?
if [[ $ret == 0 ]]; then
  echo -e "\033[0;32mshell command completed with exit code $ret\033[0m"
else
  echo -e "\033[0;31mshell command completed with exit code $ret\033[0m"
fi
kill -KILL $pid2
exit $ret
