defmodule PolyglotWatcher.Elixir.Usage do
  @prefix "ex"

  def usage do
    [
      {:yellow, "# Elixir\n\n"},
      {:yellow, "## Command line input\n\n"},
      {:white, "  • "},
      {:cyan, "#{@prefix} d "},
      {:white, " switch to "},
      {:bright, "default mode"},
      {:white, "\n"},
      {:white, "  • "},
      {:cyan, "#{@prefix} fa"},
      {:white, " switch to "},
      {:bright, "fix all mode"},
      {:white, "\n"},
      {:white, "  • "},
      {:cyan, "#{@prefix} f "},
      {:white, " switch to "},
      {:bright, "fixed mode"},
      {:white, "\n"},
      {:white, "  • "},
      {:cyan, "#{@prefix} test/example_test.exs"},
      {:white, " switch to "},
      {:bright, "fixed mode"},
      {:white, "\n"},
      {:white, "  • "},
      {:cyan, "   test/example_test.exs"},
      {:white, " switch to "},
      {:bright, "fixed mode"},
      {:white, " (same as the above command)"},
      {:white, "\n"},
      {:white, "  • "},
      {:cyan, "#{@prefix} a"},
      {:white, " runs "},
      {:green, "mix test"},
      {:white, " as a one off"},
      {:white, "\n\n"},
      {:yellow, "## Watcher Modes\n\n"},
      {:bright, "default mode"},
      {:white, "\n"},
      {:white, "  "},
      {:green, "lib/example.ex"},
      {:white, " is saved        -> runs "},
      {:green, "mix test test/example_test.exs"},
      {:white, " if the test file exists"},
      {:white, "\n"},
      {:white, "  "},
      {:green, "test/example_test.exs"},
      {:white, " is saved -> runs "},
      {:green, "mix test test/example_test.exs"},
      {:white, "\n\n"},
      {:bright, "fix all mode"},
      {:white, "\n"},
      {:white, "  "},
      {:white, "Runs a series of "},
      {:green, "mix test"},
      {:white, " commands"},
      {:white, "\n"},
      {:white, "  "},
      {:white, "minimising how many tests are run"},
      {:white, "\n"},
      {:white, "  "},
      {:white, "minimising "},
      {:green, "mix test"},
      {:white, " output on screen to one test failure at a time to reduce noise"},
      {:white, "\n"},
      {:white, "  "},
      {:white, "switch to this mode of more info"},
      {:white, "\n\n"},
      {:bright, "fixed mode"},
      {:white, "\n"},
      {:white, "  "},
      {:white, "Runs either"},
      {:white, "\n"},
      {:white, "  "},
      {:green, "mix test test/the/most/recently/failed_test.exs:34"},
      {:white, "\n"},
      {:white, "  "},
      {:white, "OR"},
      {:white, "\n"},
      {:white, "  "},
      {:green, "mix test test/the/specified/failed_test.exs:34"},
      {:white, "\n"},
      {:white, "  "},
      {:white, "when any elixir file is saved"},
      {:white, "\n"}
    ]
  end
end
